const SUPABASE_URL='https://nrwjahkcnktiqqusdzju.supabase.co';
const SUPABASE_KEY='sb_publishable_c8EiJPtAcq665YVyapwBZg_k8lultCL';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=(cents,currency='GBP')=>new Intl.NumberFormat('en-GB',{style:'currency',currency}).format((Number(cents)||0)/100);
const dt=v=>new Date(v).toLocaleString('en-GB',{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});
const state={route:'home',session:null,profile:null,categories:[],slots:[],bookings:[],favorites:new Set(),notifications:[],businesses:[],myBusiness:null,services:[],location:'Anywhere',query:'',category:'all'};
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
function openModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden');$('#modal').setAttribute('aria-hidden','false')}
function closeModal(){$('#modal').classList.add('hidden');$('#modal').setAttribute('aria-hidden','true')}
document.addEventListener('click',e=>{if(e.target.closest('[data-close-modal]'))closeModal();const r=e.target.closest('[data-route]');if(r){route(r.dataset.route)}});
function route(name){state.route=name;$$('[data-route]').forEach(x=>x.classList.toggle('active',x.dataset.route===name));render()}
function updateHeader(){const name=state.profile?.full_name||state.session?.user?.email||'R';$('#avatarBtn').textContent=name.trim().charAt(0).toUpperCase()||'R';$('#locationText').textContent=state.location;const n=state.notifications.filter(x=>!x.read_at).length;$('#notificationCount').textContent=n;$('#notificationCount').classList.toggle('hidden',!n)}
async function init(){const {data:{session}}=await sb.auth.getSession();state.session=session;await loadCore();if(session)await loadPrivate();updateHeader();render();sb.auth.onAuthStateChange(async(_event,session)=>{state.session=session;state.profile=null;state.bookings=[];state.notifications=[];state.favorites=new Set();await loadCore();if(session)await loadPrivate();updateHeader();render()})}
async function loadCore(){const [{data:cats},{data:slots},{data:businesses}]=await Promise.all([
 sb.from('categories').select('*').eq('active',true).order('sort_order'),
 sb.from('marketplace_slots').select('*').order('starts_at').limit(100),
 sb.from('businesses').select('id,name,slug,description,city,postcode,rating,review_count,logo_url,cover_url,status,category_id').eq('status','verified').limit(100)
]);state.categories=cats||[];state.slots=slots||[];state.businesses=businesses||[]}
async function loadPrivate(){const uid=state.session.user.id;const [{data:p},{data:bks},{data:favs},{data:notifs},{data:bizs}]=await Promise.all([
 sb.from('profiles').select('*').eq('id',uid).maybeSingle(),
 sb.from('bookings').select('*,services(name),businesses(name),availability_slots(starts_at,ends_at)').eq('customer_id',uid).order('created_at',{ascending:false}),
 sb.from('favorites').select('business_id').eq('user_id',uid),
 sb.from('notifications').select('*').eq('user_id',uid).order('created_at',{ascending:false}).limit(50),
 sb.from('businesses').select('*').eq('owner_id',uid).limit(1)
]);state.profile=p||null;state.bookings=bks||[];state.favorites=new Set((favs||[]).map(x=>x.business_id));state.notifications=notifs||[];state.myBusiness=bizs?.[0]||null;if(state.myBusiness){const {data:sv}=await sb.from('services').select('*').eq('business_id',state.myBusiness.id).order('created_at');state.services=sv||[]}}
function requireAuth(next){if(state.session)return true;authModal(next);return false}
function authModal(next='home'){openModal(`<div class="eyebrow">WELCOME TO REBOOKD</div><h2>Sign in or create an account</h2><div class="tabs"><button id="tabLogin" class="active">Sign in</button><button id="tabSignup">Create account</button></div><div id="authForm"></div>`);const draw=mode=>{$('#tabLogin').classList.toggle('active',mode==='login');$('#tabSignup').classList.toggle('active',mode==='signup');$('#authForm').innerHTML=`${mode==='signup'?`<div class="field"><label>Name</label><input id="authName" autocomplete="name"></div><br>`:''}<div class="field"><label>Email</label><input id="authEmail" type="email" autocomplete="email"></div><br><div class="field"><label>Password</label><input id="authPassword" type="password" autocomplete="${mode==='login'?'current-password':'new-password'}"></div><br><button class="btn btn-primary full-btn" id="authSubmit">${mode==='login'?'Sign in':'Create account'}</button>${mode==='login'?'<br><button class="btn btn-ghost full-btn" id="magicBtn">Email me a magic link</button>':''}`;$('#authSubmit').onclick=async()=>{const email=$('#authEmail').value.trim(),password=$('#authPassword').value;if(mode==='login'){const {error}=await sb.auth.signInWithPassword({email,password});if(error)return toast(error.message);toast('Signed in');closeModal();route(next)}else{const full_name=$('#authName').value.trim();const {error}=await sb.auth.signUp({email,password,options:{data:{full_name}}});if(error)return toast(error.message);toast('Account created — check your email if confirmation is enabled');closeModal()}};if($('#magicBtn'))$('#magicBtn').onclick=async()=>{const email=$('#authEmail').value.trim();const {error}=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin}});toast(error?error.message:'Magic link sent')}};$('#tabLogin').onclick=()=>draw('login');$('#tabSignup').onclick=()=>draw('signup');draw('login')}
function filteredSlots(){return state.slots.filter(s=>(state.category==='all'||s.category_slug===state.category)&&(!state.query||`${s.service_name} ${s.business_name} ${s.city||''}`.toLowerCase().includes(state.query.toLowerCase()))&&(!state.location||state.location==='Anywhere'||(s.city||'').toLowerCase().includes(state.location.toLowerCase())||(s.postcode||'').toLowerCase().includes(state.location.toLowerCase())))}
function slotCard(s){const discount=s.standard_price_cents>0?Math.round((1-s.deal_price_cents/s.standard_price_cents)*100):0;return `<article class="slot-card"><div class="slot-image"><div class="service-icon">${categoryIcon(s.category_slug)}</div><span class="discount">${discount>0?`${discount}% OFF`:'LAST MINUTE'}</span></div><div class="slot-body"><div class="slot-title-row"><div><h3>${esc(s.service_name)}</h3><div class="meta">${esc(s.business_name)} · ${esc(s.city||'')}</div></div><button class="heart" onclick="toggleFavorite('${s.business_id}')">${state.favorites.has(s.business_id)?'♥':'♡'}</button></div><div class="meta">★ ${Number(s.rating||0).toFixed(1)} (${s.review_count||0}) · ${dt(s.starts_at)} · ${s.spots_left} spot${s.spots_left===1?'':'s'} left</div><div class="price-row"><div class="price"><strong>${money(s.deal_price_cents,s.currency)}</strong>${s.standard_price_cents!==s.deal_price_cents?`<s>${money(s.standard_price_cents,s.currency)}</s>`:''}</div></div><div class="slot-actions"><button class="btn btn-soft" onclick="showSlot('${s.slot_id}')">Details</button><button class="btn btn-primary" onclick="startBooking('${s.slot_id}')">Claim slot</button></div></div></article>`}
function categoryIcon(slug){return {beauty:'✨',barber:'✂️',fitness:'🏋️',wellness:'💆',classes:'🎨',cooking:'🍳',education:'🎓',driving:'🚗',photography:'📷',pets:'🐾',automotive:'🔧',health:'🩺',sports:'🏆',home:'🏠',consulting:'💼',other:'📅'}[slug]||'📅'}
function home(){const list=filteredSlots();return `<section class="hero"><div class="hero-main"><div class="kicker">ANY BOOKING. ONE MARKETPLACE.</div><h1>Find a last-minute slot.</h1><p>Beauty, barbers, PT sessions, cooking classes, driving lessons, tutoring, massage, photography, pet care, vehicle services, workshops and more.</p><div class="search-shell"><input id="homeSearch" placeholder="Search services, businesses or locations" value="${esc(state.query)}"><select id="homeCat"><option value="all">All categories</option>${state.categories.map(c=>`<option value="${c.slug}" ${state.category===c.slug?'selected':''}>${esc(c.name)}</option>`).join('')}</select><input id="homeLoc" placeholder="Town or city" value="${state.location==='Anywhere'?'':esc(state.location)}"><button class="btn btn-primary" id="searchBtn">Search</button></div></div><div class="hero-side"><div class="hero-stat"><strong>${state.slots.length}</strong><span>live last-minute slots</span></div><div class="hero-stat"><strong>${state.categories.length}</strong><span>booking categories</span></div><div class="hero-stat"><strong>Secure</strong><span>accounts + row-level permissions</span></div></div></section><section class="section"><div class="section-head"><div><div class="kicker">EXPLORE</div><h2>Browse by category</h2></div></div><div class="category-grid">${state.categories.map(c=>`<button class="category-card" onclick="pickCategory('${c.slug}')"><i>${categoryIcon(c.slug)}</i><b>${esc(c.name)}</b></button>`).join('')}</div></section><section class="section"><div class="section-head"><div><div class="kicker">AVAILABLE NOW</div><h2>Last-minute deals</h2></div><span class="meta">${list.length} found</span></div><div class="grid">${list.length?list.map(slotCard).join(''):'<div class="empty">No matching slots yet. Try another category or location.</div>'}</div></section>`}
function explore(){const list=filteredSlots();return `<section class="section"><div class="section-head"><div><div class="kicker">DISCOVER</div><h2>Explore Rebookd</h2><p>Search across every appointment-based category.</p></div></div><div class="search-shell"><input id="exploreSearch" placeholder="Search" value="${esc(state.query)}"><select id="exploreCat"><option value="all">All categories</option>${state.categories.map(c=>`<option value="${c.slug}" ${state.category===c.slug?'selected':''}>${esc(c.name)}</option>`).join('')}</select><input id="exploreLoc" placeholder="Town or city" value="${state.location==='Anywhere'?'':esc(state.location)}"><button class="btn btn-primary" id="exploreBtn">Apply</button></div><br><div class="grid">${list.length?list.map(slotCard).join(''):'<div class="empty">No matching slots.</div>'}</div></section>`}
function bookings(){if(!state.session)return `<section class="section"><div class="empty"><h3>Your bookings live here</h3><p>Sign in to see and manage them.</p><button class="btn btn-primary" onclick="authModal('bookings')">Sign in</button></div></section>`;return `<section class="section"><div class="section-head"><div><div class="kicker">YOUR BOOKINGS</div><h2>Bookings</h2></div></div><div class="list">${state.bookings.length?state.bookings.map(b=>`<div class="booking-card"><div><h3>${esc(b.services?.name||'Booking')}</h3><div class="meta">${esc(b.businesses?.name||'')} · ${b.availability_slots?.starts_at?dt(b.availability_slots.starts_at):''}</div><div class="meta">Code ${esc(b.booking_code)} · ${money(b.amount_cents,b.currency)}</div></div><div><span class="status ${b.status}">${esc(b.status)}</span>${!['cancelled','completed','refunded'].includes(b.status)?`<br><br><button class="btn btn-danger small" onclick="cancelBooking('${b.id}')">Cancel</button>`:''}</div></div>`).join(''):'<div class="empty">No bookings yet.</div>'}</div></section>`}
function saved(){if(!state.session)return `<section class="section"><div class="empty"><h3>Save businesses you love</h3><button class="btn btn-primary" onclick="authModal('saved')">Sign in</button></div></section>`;const favs=state.businesses.filter(b=>state.favorites.has(b.id));return `<section class="section"><div class="section-head"><div><div class="kicker">FAVOURITES</div><h2>Saved businesses</h2></div></div><div class="grid">${favs.length?favs.map(b=>`<article class="business-card"><div class="slot-image"><div class="service-icon">★</div></div><div class="slot-body"><h3>${esc(b.name)}</h3><div class="meta">${esc(b.city||'')} · ★ ${Number(b.rating||0).toFixed(1)}</div><p class="meta">${esc(b.description||'')}</p><button class="btn btn-soft full-btn" onclick="toggleFavorite('${b.id}')">Remove</button></div></article>`).join(''):'<div class="empty">Nothing saved yet.</div>'}</div></section>`}
function notifications(){if(!state.session)return `<section class="section"><div class="empty">Sign in to see notifications.</div></section>`;return `<section class="section"><div class="section-head"><div><div class="kicker">UPDATES</div><h2>Notifications</h2></div><button class="btn btn-soft" onclick="markAllRead()">Mark all read</button></div><div class="list">${state.notifications.length?state.notifications.map(n=>`<div class="list-item"><div><h4>${esc(n.title)}</h4><div class="meta">${esc(n.body||'')}</div></div><span class="status ${n.read_at?'':'live'}">${n.read_at?'read':'new'}</span></div>`).join(''):'<div class="empty">No notifications yet.</div>'}</div></section>`}
function profile(){if(!state.session)return `<section class="section"><div class="empty"><h3>Join Rebookd</h3><p>Create an account to book, save businesses or list your own business.</p><button class="btn btn-primary" onclick="authModal('profile')">Sign in / create account</button></div></section>`;const p=state.profile||{};return `<section class="section"><div class="profile-head"><div class="profile-avatar">${esc((p.full_name||state.session.user.email||'R')[0].toUpperCase())}</div><div><div class="kicker">ACCOUNT</div><h2>${esc(p.full_name||'Your profile')}</h2><div class="meta">${esc(state.session.user.email||'')} · ${esc(p.role||'customer')}</div></div></div><br><div class="split"><div class="panel"><h3>Profile</h3><div class="field"><label>Name</label><input id="profName" value="${esc(p.full_name||'')}"></div><br><div class="field"><label>Phone</label><input id="profPhone" value="${esc(p.phone||'')}"></div><br><div class="check-row"><input type="checkbox" id="profMarketing" ${p.marketing_opt_in?'checked':''}><label>Product updates and offers</label></div><br><button class="btn btn-primary" onclick="saveProfile()">Save profile</button></div><div class="panel"><h3>For businesses</h3>${state.myBusiness?`<p><b>${esc(state.myBusiness.name)}</b></p><div class="meta">Status: ${esc(state.myBusiness.status)}</div><br><button class="btn btn-primary" onclick="route('business')">Open business dashboard</button>`:`<p class="meta">List any legitimate booking-based business and publish cancelled or spare slots.</p><button class="btn btn-primary" onclick="businessOnboarding()">List my business</button>`}<br><br><button class="btn btn-ghost" onclick="logout()">Sign out</button></div></div></section>`}
async function loadBusinessData(){if(!state.myBusiness)return;const [{data:sv},{data:slots},{data:bks}]=await Promise.all([sb.from('services').select('*').eq('business_id',state.myBusiness.id).order('created_at'),sb.from('availability_slots').select('*,services(name)').eq('business_id',state.myBusiness.id).order('starts_at',{ascending:false}).limit(100),sb.from('bookings').select('*,profiles(full_name,email),services(name),availability_slots(starts_at)').eq('business_id',state.myBusiness.id).order('created_at',{ascending:false}).limit(100)]);state.services=sv||[];state.businessSlots=slots||[];state.businessBookings=bks||[]}
async function business(){if(!requireAuth('business'))return '<section class="section"></section>';if(!state.myBusiness)return `<section class="section"><div class="empty"><h3>No business profile yet</h3><p>Create one from your Profile page.</p><button class="btn btn-primary" onclick="businessOnboarding()">Create business</button></div></section>`;await loadBusinessData();const b=state.myBusiness;return `<section class="section"><div class="section-head"><div><div class="kicker">BUSINESS DASHBOARD</div><h2>${esc(b.name)}</h2><p>${esc(b.city||'')} · <span class="status ${b.status}">${esc(b.status)}</span></p></div><button class="btn btn-primary" onclick="newServiceModal()">+ Service</button></div><div class="stats"><div class="stat"><strong>${state.services.length}</strong><span>services</span></div><div class="stat"><strong>${(state.businessSlots||[]).filter(x=>x.active).length}</strong><span>slots</span></div><div class="stat"><strong>${(state.businessBookings||[]).length}</strong><span>bookings</span></div><div class="stat"><strong>${(state.businessBookings||[]).filter(x=>x.payment_status==='paid').reduce((a,x)=>a+x.business_net_cents,0)/100|0}</strong><span>£ net recorded</span></div></div><br><div class="split"><div class="panel"><div class="section-head"><div><h3>Services</h3></div><button class="btn btn-soft small" onclick="newSlotModal()">Post slot</button></div><div class="list">${state.services.length?state.services.map(s=>`<div class="list-item"><div><b>${esc(s.name)}</b><div class="meta">${s.duration_minutes} min · ${money(s.standard_price_cents,s.currency)} · capacity ${s.capacity}</div></div><span class="status ${s.active?'live':''}">${s.active?'active':'paused'}</span></div>`).join(''):'<div class="empty">Add your first service.</div>'}</div></div><div class="panel"><h3>Recent bookings</h3><div class="list">${(state.businessBookings||[]).length?state.businessBookings.slice(0,10).map(x=>`<div class="list-item"><div><b>${esc(x.services?.name||'Booking')}</b><div class="meta">${esc(x.profiles?.full_name||x.profiles?.email||'Customer')} · ${x.availability_slots?.starts_at?dt(x.availability_slots.starts_at):''}</div></div><span class="status ${x.status}">${esc(x.status)}</span></div>`).join(''):'<div class="empty">No bookings yet.</div>'}</div></div></div><br><div class="panel"><h3>Payments & payouts</h3><p class="meta">${b.payouts_enabled?'Payout account is connected.':'Connect Stripe before taking real payments. The backend endpoints are included in this project and activate once Stripe environment variables are added.'}</p><button class="btn btn-primary" onclick="setupPayouts()">${b.payouts_enabled?'Manage payout account':'Set up payouts'}</button></div></section>`}
function render(){updateHeader();const app=$('#app');if(state.route==='home')app.innerHTML=home();else if(state.route==='explore')app.innerHTML=explore();else if(state.route==='bookings')app.innerHTML=bookings();else if(state.route==='saved')app.innerHTML=saved();else if(state.route==='notifications')app.innerHTML=notifications();else if(state.route==='profile')app.innerHTML=profile();else if(state.route==='business'){app.innerHTML='<section class="section"><div class="empty">Loading business dashboard…</div></section>';business().then(html=>app.innerHTML=html)}wirePage()}
function wirePage(){const bind=(id,fn)=>{const el=$(id);if(el)el.onclick=fn};bind('#searchBtn',()=>{state.query=$('#homeSearch').value;state.category=$('#homeCat').value;state.location=$('#homeLoc').value.trim()||'Anywhere';route('explore')});bind('#exploreBtn',()=>{state.query=$('#exploreSearch').value;state.category=$('#exploreCat').value;state.location=$('#exploreLoc').value.trim()||'Anywhere';render()})}
window.pickCategory=slug=>{state.category=slug;route('explore')};
window.showSlot=id=>{const s=state.slots.find(x=>x.slot_id===id);if(!s)return;openModal(`<div class="eyebrow">LAST-MINUTE SLOT</div><h2>${esc(s.service_name)}</h2><p><b>${esc(s.business_name)}</b></p><p class="meta">${esc(s.city||'')} · ★ ${Number(s.rating||0).toFixed(1)} · ${dt(s.starts_at)} · ${s.duration_minutes} min</p><div class="price"><strong>${money(s.deal_price_cents,s.currency)}</strong> <s>${money(s.standard_price_cents,s.currency)}</s></div><br><button class="btn btn-primary full-btn" onclick="startBooking('${s.slot_id}')">Claim this slot</button>`)};
window.startBooking=async id=>{if(!requireAuth('bookings'))return;const s=state.slots.find(x=>x.slot_id===id);if(!s)return;openModal(`<div class="eyebrow">CONFIRM</div><h2>${esc(s.service_name)}</h2><p>${esc(s.business_name)} · ${dt(s.starts_at)}</p><p class="price"><strong>${money(s.deal_price_cents,s.currency)}</strong></p>${s.capacity>1?`<div class="field"><label>Places</label><input id="bookQty" type="number" min="1" max="${s.spots_left}" value="1"></div><br>`:''}<button class="btn btn-primary full-btn" id="reserveBtn">Reserve & continue to payment</button>`);$('#reserveBtn').onclick=async()=>{const qty=Math.max(1,Number($('#bookQty')?.value||1));const {data,error}=await sb.rpc('book_slot',{p_slot_id:id,p_quantity:qty,p_platform_fee_bps:1000});if(error)return toast(error.message);const bookingId=data;try{const res=await fetch('/api/create-checkout',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${state.session.access_token}`},body:JSON.stringify({booking_id:bookingId})});const out=await res.json();if(res.ok&&out.url){location.href=out.url;return}toast(out.error||'Payment setup is not active yet. Your slot is reserved as pending.')}catch{toast('Payment setup is not active yet. Your slot is reserved as pending.')}closeModal();await loadCore();await loadPrivate();route('bookings')}};
window.cancelBooking=async id=>{if(!confirm('Cancel this booking?'))return;const {error}=await sb.rpc('cancel_booking',{p_booking_id:id,p_reason:'Cancelled by customer'});if(error)return toast(error.message);toast('Booking cancelled');await loadCore();await loadPrivate();render()};
window.toggleFavorite=async businessId=>{if(!requireAuth('saved'))return;const uid=state.session.user.id;if(state.favorites.has(businessId)){const {error}=await sb.from('favorites').delete().eq('user_id',uid).eq('business_id',businessId);if(error)return toast(error.message);state.favorites.delete(businessId)}else{const {error}=await sb.from('favorites').insert({user_id:uid,business_id:businessId});if(error)return toast(error.message);state.favorites.add(businessId)}render()};
window.markAllRead=async()=>{if(!state.session)return;await sb.from('notifications').update({read_at:new Date().toISOString()}).eq('user_id',state.session.user.id).is('read_at',null);await loadPrivate();render()};
window.saveProfile=async()=>{const {error}=await sb.from('profiles').update({full_name:$('#profName').value.trim(),phone:$('#profPhone').value.trim(),marketing_opt_in:$('#profMarketing').checked}).eq('id',state.session.user.id);if(error)return toast(error.message);toast('Profile saved');await loadPrivate();render()};
window.logout=async()=>{await sb.auth.signOut();route('home')};
window.businessOnboarding=()=>{if(!requireAuth('profile'))return;openModal(`<div class="eyebrow">LIST YOUR BUSINESS</div><h2>Create a Rebookd business</h2><div class="form-grid"><div class="field"><label>Business name</label><input id="boName"></div><div class="field"><label>Category</label><select id="boCat">${state.categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>City</label><input id="boCity"></div><div class="field"><label>Postcode</label><input id="boPost"></div><div class="field full"><label>Description</label><textarea id="boDesc"></textarea></div></div><br><button class="btn btn-primary full-btn" id="boCreate">Create business</button>`);$('#boCreate').onclick=async()=>{const name=$('#boName').value.trim();if(!name)return toast('Business name required');const slug=`${name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}-${Math.random().toString(36).slice(2,6)}`;const {data,error}=await sb.rpc('create_business',{p_name:name,p_slug:slug,p_category_id:$('#boCat').value,p_description:$('#boDesc').value.trim(),p_city:$('#boCity').value.trim(),p_postcode:$('#boPost').value.trim(),p_country_code:'GB'});if(error)return toast(error.message);toast('Business created. Complete verification before public listing.');closeModal();await loadPrivate();route('business')}};
window.newServiceModal=()=>{openModal(`<div class="eyebrow">NEW SERVICE</div><h2>Add a service</h2><div class="form-grid"><div class="field"><label>Name</label><input id="svName"></div><div class="field"><label>Duration (minutes)</label><input id="svDuration" type="number" value="60" min="5"></div><div class="field"><label>Normal price (£)</label><input id="svPrice" type="number" step="0.01"></div><div class="field"><label>Capacity</label><input id="svCapacity" type="number" value="1" min="1"></div><div class="field full"><label>Description</label><textarea id="svDesc"></textarea></div></div><br><button class="btn btn-primary full-btn" id="svCreate">Add service</button>`);$('#svCreate').onclick=async()=>{const payload={business_id:state.myBusiness.id,name:$('#svName').value.trim(),description:$('#svDesc').value.trim(),duration_minutes:Number($('#svDuration').value),standard_price_cents:Math.round(Number($('#svPrice').value)*100),currency:'GBP',capacity:Number($('#svCapacity').value)};const {error}=await sb.from('services').insert(payload);if(error)return toast(error.message);toast('Service added');closeModal();render()}};
window.newSlotModal=()=>{if(!state.services.length)return toast('Add a service first');openModal(`<div class="eyebrow">POST AVAILABILITY</div><h2>Publish a last-minute slot</h2><div class="form-grid"><div class="field"><label>Service</label><select id="slService">${state.services.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></div><div class="field"><label>Start</label><input id="slStart" type="datetime-local"></div><div class="field"><label>Deal price (£)</label><input id="slPrice" type="number" step="0.01"></div><div class="field"><label>Capacity</label><input id="slCapacity" type="number" value="1" min="1"></div></div><br><button class="btn btn-primary full-btn" id="slCreate">Publish slot</button>`);$('#slCreate').onclick=async()=>{const service=state.services.find(s=>s.id===$('#slService').value);const start=new Date($('#slStart').value);if(!service||Number.isNaN(start.getTime()))return toast('Choose a service and start time');const end=new Date(start.getTime()+service.duration_minutes*60000);const deal=Math.round(Number($('#slPrice').value)*100);if(deal<=0||deal>=service.standard_price_cents)return toast('Deal price must be below normal price');const discount=Math.round((1-deal/service.standard_price_cents)*100);const {error}=await sb.from('availability_slots').insert({service_id:service.id,business_id:state.myBusiness.id,starts_at:start.toISOString(),ends_at:end.toISOString(),capacity:Number($('#slCapacity').value)||service.capacity,deal_price_cents:deal,discount_percent:discount,source:'manual'});if(error)return toast(error.message);toast('Slot published');closeModal();await loadCore();render()}};
window.setupPayouts=async()=>{if(!state.session||!state.myBusiness)return;try{const res=await fetch('/api/stripe-connect',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${state.session.access_token}`},body:JSON.stringify({business_id:state.myBusiness.id})});const out=await res.json();if(res.ok&&out.url)return location.href=out.url;toast(out.error||'Stripe is not configured yet.')}catch{toast('Stripe is not configured yet.')}};
$('#locationBtn').onclick=()=>openModal(`<div class="eyebrow">LOCATION</div><h2>Where should we search?</h2><div class="field"><label>Town, city or postcode</label><input id="locInput" value="${state.location==='Anywhere'?'':esc(state.location)}" placeholder="e.g. Watford"></div><br><button class="btn btn-primary full-btn" id="locSave">Use this location</button>`);
document.addEventListener('click',e=>{if(e.target?.id==='locSave'){state.location=$('#locInput').value.trim()||'Anywhere';closeModal();updateHeader();render()}});
init();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
